name: "🐞 Bug report"
description: "Report a reproducible bug"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Thanks for reporting a bug. Please fill out the details below."
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: "Steps to reproduce the behavior."
      placeholder: "1. ...\n2. ...\n3. ..."
    validations:
      required: true
  - type: textarea
    id: expected-actual
    attributes:
      label: Expected vs actual behavior
      description: "What you expected to happen vs what actually happened."
      placeholder: "Expected: ...\nActual: ..."
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment info
      description: "OS, Node.js version, and any other relevant details."
      placeholder: "OS: ...\nNode: ...\nOther: ..."
    validations:
      required: true
