name: "✨ Feature request"
description: "Suggest a new feature or improvement"
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "Thanks for the idea. Share the problem and the proposal so we can evaluate impact and scope."
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: "What pain point are you experiencing today?"
      placeholder: "Describe the problem, who is affected, and why it matters."
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: "What change would you like to see?"
      placeholder: "Describe your preferred solution and how it would work."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: "Optional: other solutions or workarounds you considered."
      placeholder: "List alternatives and why they are not ideal."
    validations:
      required: false
  - type: dropdown
    id: impact
    attributes:
      label: Expected impact
      description: "How broadly would this affect users?"
      options:
        - "Low (nice-to-have improvement)"
        - "Medium (meaningful productivity/usability gain)"
        - "High (unblocks critical workflows)"
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: "Optional: links, screenshots, related issues, or technical notes."
      placeholder: "Anything else that helps with triage."
    validations:
      required: false
