name: "❓ Question"
description: "Ask a question (consider Discussions if enabled)"
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: "Ask your question with enough context for a quick, accurate answer."
  - type: textarea
    id: goal
    attributes:
      label: What are you trying to do?
      description: "Describe your goal and where you are blocked."
      placeholder: "I want to ... but I am blocked at ..."
    validations:
      required: true
  - type: textarea
    id: attempted
    attributes:
      label: What have you tried?
      description: "Share commands, code snippets, or docs/issues you already checked."
      placeholder: "I tried ... and checked ..."
    validations:
      required: true
  - type: textarea
    id: error-output
    attributes:
      label: Error output or logs (optional)
      description: "Paste any relevant error messages, stack traces, or output."
      placeholder: "Paste logs or errors here."
      render: shell
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment info
      description: "Optional: OS, Node.js version, package version, and other relevant details."
      placeholder: "OS: ...\nNode: ...\nOther: ..."
    validations:
      required: false
