import type { CodedError } from '@slack/bolt';
import { logger } from '@sniptail/core/logger.js';
import { registerClearBeforeCommand } from './features/commands/clearBefore.js';
import { registerRepoAddModalCommand } from './features/commands/repoAddModalCommand.js';
import { registerRepoRemoveModalCommand } from './features/commands/repoRemoveModalCommand.js';
import { registerAskCommand } from './features/commands/ask.js';
import { registerSlackExploreCommand } from './features/commands/slackExploreCommand.js';
import { registerPlanCommand } from './features/commands/plan.js';
import { registerBootstrapCommand } from './features/commands/bootstrap.js';
import { registerImplementCommand } from './features/commands/implement.js';
import { registerRunCommand } from './features/commands/slackRunCommand.js';
import { registerAgentCommand } from './features/commands/agent.js';
import { registerUsageCommand } from './features/commands/usage.js';
import { registerAskFromJobAction } from './features/actions/askFromJob.js';
import { registerSlackExploreFromJobAction } from './features/actions/slackExploreFromJobAction.js';
import { registerPlanFromJobAction } from './features/actions/planFromJob.js';
import { registerClearJobAction } from './features/actions/clearJob.js';
import { registerAnswerQuestionsAction } from './features/actions/answerQuestions.js';
import { registerImplementFromJobAction } from './features/actions/implementFromJob.js';
import { registerRunFromJobAction } from './features/actions/runFromJob.js';
import { registerReviewFromJobAction } from './features/actions/reviewFromJob.js';
import { registerWorktreeCommandsAction } from './features/actions/worktreeCommands.js';
import { registerApprovalActions } from './features/actions/approvalActions.js';
import { registerAgentFollowUpActions } from './features/actions/agentFollowUp.js';
import { registerAgentPermissionActions } from './features/actions/agentPermission.js';
import { registerAgentQuestionActions } from './features/actions/agentQuestion.js';
import { registerAgentStopAction } from './features/actions/agentStop.js';
import { registerRunActionSelectOptions } from './features/actions/runActionSelect.js';
import { registerAppMentionEvent } from './features/events/appMention.js';
import { registerDmMentionEvent } from './features/events/dmMentionEvent.js';
import { registerAskSubmitView } from './features/views/askSubmit.js';
import { registerSlackExploreSubmitView } from './features/views/slackExploreSubmitView.js';
import { registerPlanSubmitView } from './features/views/planSubmit.js';
import { registerAnswerQuestionsSubmitView } from './features/views/answerQuestionsSubmit.js';
import { registerBootstrapSubmitView } from './features/views/bootstrapSubmit.js';
import { registerImplementSubmitView } from './features/views/implementSubmit.js';
import { registerRepoAddModalSubmit } from './features/views/repoAddModalSubmit.js';
import { registerRepoRemoveModalSubmit } from './features/views/repoRemoveModalSubmit.js';
import { registerRunSubmitView } from './features/views/slackRunSubmitView.js';
import { registerAgentSubmitView } from './features/views/agentSubmit.js';
import type { SlackHandlerContext } from './features/context.js';

export function registerSlackHandlers(context: SlackHandlerContext): void {
  registerAskCommand(context);
  registerRepoAddModalCommand(context);
  registerRepoRemoveModalCommand(context);
  registerSlackExploreCommand(context);
  registerPlanCommand(context);
  registerImplementCommand(context);
  registerRunCommand(context);
  registerAgentCommand(context);
  registerBootstrapCommand(context);
  registerClearBeforeCommand(context);
  registerUsageCommand(context);
  registerAskFromJobAction(context);
  registerSlackExploreFromJobAction(context);
  registerPlanFromJobAction(context);
  registerImplementFromJobAction(context);
  registerRunFromJobAction(context);
  registerReviewFromJobAction(context);
  registerWorktreeCommandsAction(context);
  registerClearJobAction(context);
  registerApprovalActions(context);
  registerAgentStopAction(context);
  registerAgentFollowUpActions(context);
  registerAgentPermissionActions(context);
  registerAgentQuestionActions(context);
  registerRunActionSelectOptions(context);
  registerAnswerQuestionsAction(context);
  registerAppMentionEvent(context);
  registerDmMentionEvent(context);
  registerBootstrapSubmitView(context);
  registerRepoAddModalSubmit(context);
  registerRepoRemoveModalSubmit(context);
  registerAskSubmitView(context);
  registerSlackExploreSubmitView(context);
  registerPlanSubmitView(context);
  registerAnswerQuestionsSubmitView(context);
  registerImplementSubmitView(context);
  registerRunSubmitView(context);
  registerAgentSubmitView(context);

  // eslint-disable-next-line @typescript-eslint/require-await
  context.app.error(async (err: CodedError) => {
    logger.error({ err }, 'Slack app error');
  });
}
